package comp1110.ass2;

public class Raft {
    // this class can be deleted depending on the challenge


    /**
     *This method is to add raftTiles to the board according to challenge string.
     * <p>
     *In this part of initializing the game, all added raft tiles are 3*3 shape. And the coordiante
     *refers to the top left location.
     * <p>
     *Return nothing, just update the Square[][] board.
     * @param board the Square[][] representing the play board. This is generated by putting 4 islands together
     * @param raftSubstring Substring from challenge. eg. "01215"
     *              First character is number between 0 and 3 representing the ID of the raft card.
     *              Then,every 2 digit represent a row index or a column index on the play board.
     */
    public static void addRaft(Square[][] board, String raftSubstring) {
//        System.out.println(raftSubstring);
        int raftId = Integer.parseInt(raftSubstring.substring(0,1));
        int cardAtRow = Integer.parseInt(raftSubstring.substring(1, 3));
        int cardAtColumn = Integer.parseInt(raftSubstring.substring(3));
        //this is a length of 9 string
        String raftCardString = Utility.RAFT_CARDS[raftId].substring(1);

//        System.out.println("ID: "+ raftId +"左上行列"+ cardAtRow +" "+ cardAtColumn);
//        System.out.println("对应utility: "+raftCardString);

        //rotate through a 3*3 raft card
        int index = 0;
        for (int r = cardAtRow; r < cardAtRow + 3; r++) {
            for (int c = cardAtColumn; c < cardAtColumn + 3; c++) {
                board[r][c].setColour(Colour.fromChar(raftCardString.charAt(index)));
                index++;
            }
        }
    }
}
